### ISSUE TITLE
Lose game if you are not able to move.

### ISSUE THREAD

**Issue by FelRho** [Benhatsdrauf/MuehleOnline#83]
If the opponent is not able to move in his turn, he should lose the game imitatively. Currently game is stuck until opponent moves, which is not possible.

**Comment by Benhatsdrauf** [comment]
I dont  know... i am no expert in nine mans morris but i think we should check the official rules for this.
Its possible that if your opponent happens to get into this position you automatically win the game 🤔 
But if there is no official way to handle this case then i think your idea is a good solution for this problem 👍

**Comment by FelRho** [comment]
Good point, turns out ChatGTP does not know all that much about nine mens morrise. Here is the proper [source (in german)](https://de.wikipedia.org/wiki/M%C3%BChle_(Spiel)#:~:text=Kann%20ein%20Spieler%20keinen%20Stein,hat%20er%20das%20Spiel%20verloren.).
The rules state that if you can not move you lose instantly. The ticket will be adjusted accordingly.
